---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
#  - name: centos-6.4

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[apt::default]
      - recipe[artifact-deployer::default]
    attributes: {
      artifacts: {
        junit1: {
          enabled: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/default_suite",
          owner: "root"
        },
        junit2: {
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/disabled_suite",
          owner: "root"
        },
        junit3: {
          enabled: true,
          unzip: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/subfolder_suite",
          subfolder: "META-INF/\\*",
          owner: "root"
        }
      }
    }
